### ISSUE TITLE
Move AWS Types to ruby Contracts for better and more flexible validation?

### ISSUE THREAD

**Issue by pvdvreede** [cfndsl/cfndsl#222]
Hi there,

One of the things I really love about cfndsl is that fast feedback you get when compiling for missing or incorrect resource names, parameters and references. 

I notice at the moment that all references and properties are defined in a yaml file with a bit of data about the type. I would like to see if there is any appetite to move that to something like ruby's Contracts gem: https://github.com/egonSchiele/contracts.ruby.

Given we are manually defining the type already, if we were to define the types in the contracts gem DSL it appears as though we can start to get better validation around the Property types and the JSON structures so that more mistakes can be caught without having to deploy.

For example instead of just defining JSON for a IAM Policy Statement we can type the hash that must be given like so:

``` ruby
IamPolicyStatementType = {
  "Id" => String,
  "Effect" => Enum["Allow", "Deny"],
  "Action" => Or[ArrayOf[String], String],
  "Resource" => Or[ArrayOf[String], String]
}
```

If I was to volunteer to convert all yaml types to these ruby contract types, is this something that can be integrated into cfndsl? If so where in the codebase would this need to be integrated? Or is this something that people are not interested in?

**Comment by pvdvreede** [comment]
Thinking about this, what I might do is write my own gem that takes a json file, converts it to a hash and then validates it as a Cloudformation, just to see if there is any interest, and at least I can use it as a post processor after cfndsl if no one else is interested.

**Comment by jyaworski** [comment]
I'd like to see this implemented also. It would require less processing overall and use a more ruby-centric solution.

**Comment by pvdvreede** [comment]
I have started a project to validate json cloudformation templates: https://github.com/pvdvreede/cfn_validator to see how easy it is and how valuable it is. 

The tests are using the AWS sample templates to make sure it is not giving false negatives. I suppose the idea is to start very permissive, that way it can be iterated over time with more checks without breaking anything.

**Comment by kornypoet** [comment]
This could be very interesting. AWS CloudFormation Resources often have quite a few restrictions, some of them documented, some not. I would be in favor of implementing this as long as the current dsl structure is still supported.

Right now, we define resources as methods on a template, with a corresponding entry in a hash pointing to a class definition. The properties of the resource are defined as methods on that class. I see how `Contracts` can give us validation on the property methods. Can it give us guarantees on the resource as well? Some resources have required properties. One of the issues I foresee is that most templates declare resources using block syntax. Can `Contracts` determine whether specific properties have been declared?

Lastly, it looks like your current approach is to validate the template after it's already been serialized. Since we will have to declare a `Contracts` validation set and types set, it seems most logical to group those together, ie, have validation fields within the types set. Can we use implement your idea within the context of the current `types.yaml` files? The methods are being dynamically defined from that file, perhaps contracts could be as well?

**Comment by pvdvreede** [comment]
Thanks for the input @jyaworski and @kornypoet. I have been trying to create a validator tool with contracts.ruby over the last 3 days and have had good success in terms of being able to create declarative types that cover most cases and allow for really fine grained validations.

The only real issue is that contracts.ruby does not really support error feedback for recursive types, which is sadly a large issue because currently the tool can only tell you its not valid, but not why. Hopefully contracts.ruby can work on this, see https://github.com/egonSchiele/contracts.ruby/issues/222 for updates.

As to your specific questions @kornypoet I think there might be some big changes required to dynamically generate the current API from the types created. Perhaps in the future cfndsl could require my gem that exposes all the types as a Ruby API and generate them with some custom mangling to keep the cfndsl API the same. Or change the cfndsl API to build a hash (mirroring the cloudformation json) dynamically from the method calls using `method_missing` et al and then validate that hash with cfn_validator, thus not requiring a list of types at bootup time.

Separating out the types into a different gem means people could also validate their cloudformations even if they do not use cfndsl so I think it is nice to continue work on the validator gem separately as it has wider application than just cfndsl users. I can tackle the error reporting issues and see if people use it, and then revisit the possibility of integrating with cfndsl later.

Are we able to keep this issue open for the time being as a reminder?

**Comment by kornypoet** [comment]
Moving to stevenjack/cfndsl#257

**Comment by lwoggardner** [comment]
I think this is superceded by the fact we generate types from the AWS provided spec.
