### ISSUE TITLE
Condition Statement removing duplicates & causing issues

### ISSUE THREAD

**Issue by bksaurabh96** [cfndsl/cfndsl#231]
Hi Team,

While executing the DSL, It's removing the duplicate content. Please see the below DSL and Desired JSON output.

**DSL Code**
`Condition("Is-EC2-VPC", { "Fn::Or": ["Fn::Equals": [(Ref("AWS::Region")), "eu-central-1"], "Fn::Equals": [(Ref("AWS::Region")), "cn-north-1"] , "Fn::Equals": [(Ref("AWS::Region")), "ap-northeast-2"] ]})`

**Current Output:**
vagrant@vagrant:/vagrant/test_cfndsl$ cfndsl wb.rb -v --disable-binding | json_pp > cfn
Loading template file /vagrant/test_cfndsl/wb.rb
/vagrant/test_cfndsl/wb.rb:86: warning: key :"Fn::Equals" is duplicated and overwritten on line 86
/vagrant/test_cfndsl/wb.rb:86: warning: key :"Fn::Equals" is duplicated and overwritten on line 86
Writing to STDOUT
vagrant@vagrant:/vagrant/test_cfndsl$ cat cfn
{
   "AWSTemplateFormatVersion" : "2010-09-09",
   "Conditions" : {
      "Is-EC2-VPC" : {
         "Fn::Or" : [
            {
               "Fn::Equals" : [
                  {
                     "Ref" : "AWS::Region"
                  },
                  "ap-northeast-2"
               ]
            }
         ]
      },
      "Is-EC2-Classic" : {
         "Fn::Not" : [
            {
               "Condition" : "Is-EC2-VPC"
            }
         ]
      }
   }
}

**Desired Output:**

"Conditions" : {
    "Is-EC2-VPC"     : { "Fn::Or" : [ {"Fn::Equals" : [{"Ref" : "AWS::Region"}, "eu-central-1" ]},
                                      {"Fn::Equals" : [{"Ref" : "AWS::Region"}, "cn-north-1" ]},
                                      {"Fn::Equals" : [{"Ref" : "AWS::Region"}, "ap-northeast-2" ]}]},
    "Is-EC2-Classic" : { "Fn::Not" : [{ "Condition" : "Is-EC2-VPC"}]}
  }

**Comment by kornypoet** [comment]
Looking into this

**Comment by kornypoet** [comment]
@bksaurabh96 So I found a couple of things:

What you are trying to do in `cfndsl` is possible, but not the way you've specified it. In order to take advantage of the dsl, when using the functions, they have to be invoked as a method. You have them specified as a key in a hash.

```ruby
{ 'Fn::Equals' => [condition] }
# vs
FnEquals([condition])
```

Secondly, in your desired output you mention wanting a second condition. You don't have it in your original dsl entry. If you were to specify it, you would need a second `Condition` call.

```ruby
Condition(:one, condition)
Condition(:two, condition)
```

All method invocations will be collected when transforming to JSON. In order to get your desired output, write your dsl file like so:

```ruby
# condition.rb
CloudFormation do
  Condition('Is-EC2-VPC',
            FnOr([
                   FnEquals(Ref('AWS::Region'), 'eu-central-1'),
                   FnEquals(Ref('AWS::Region'), 'cn-north-1'),
                   FnEquals(Ref('AWS::Region'), 'ap-northeast-2')
                 ]))
  Condition('Is-EC2-Classic', FnNot([{ 'Condition' => 'Is-EC2-VPC' }]))
end
```

Generate your output (with pretty json) with `cfndsl -b -p condition.rb`:

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Conditions": {
    "Is-EC2-VPC": {
      "Fn::Or": [
        {
          "Fn::Equals": [
            {
              "Ref": "AWS::Region"
            },
            "eu-central-1"
          ]
        },
        {
          "Fn::Equals": [
            {
              "Ref": "AWS::Region"
            },
            "cn-north-1"
          ]
        },
        {
          "Fn::Equals": [
            {
              "Ref": "AWS::Region"
            },
            "ap-northeast-2"
          ]
        }
      ]
    },
    "Is-EC2-Classic": {
      "Fn::Not": [
        {
          "Condition": "Is-EC2-VPC"
        }
      ]
    }
  }
}
```

Conditions and functions are a little kludgy in CloudFormation, and while `cfndsl` tries to streamline some things for you, it can still be a little opaque to users. We will look into clarifying this functionality better. Hope this helps.

**Comment by cmaxwellau** [comment]
This seems to be more of a combination of the limitations when trying to represent a json structure as a ruby hash, and not using the dsl as intended.

@kornypoet does this need to stay open?
