### ISSUE TITLE
Handle Serialization Generically

### ISSUE THREAD

**Issue by kornypoet** [cfndsl/cfndsl#248]
From this PR stevenjack/cfndsl#243

Currently, there are a myriad of references all throughout the code to JSON. With the advent of CloudFormation accepting YAML, we should revisit the serialization process and perhaps break it into steps and generalize some specifics.

**Comment by cmaxwellau** [comment]
Given that json is a subset of YAML, would it make sense to switch to YAML as core?

**Comment by gergnz** [comment]
It could possibly make sense in 1.0 @cmaxwellau. I hadn't considered it. There is a 1.0.0.pre branch that's probably only a little bit behind master at the moment, I was waiting on some fixes from @lwoggardner to come in before considering a release. Feel free to take a stab at it. I would be very grateful.

**Comment by cmaxwellau** [comment]
@gergnz I'll have a look at whats involved this week. I wrote YAML support for  [cfn2dsl](https://github.com/allinwonder/cfn2dsl/pull/19) a few weeks ago so it's pretty fresh. Native rb yaml parsing (as currently used for json->yaml) does some wierd things, so I've been directly using the underlying psych library.

**Comment by gergnz** [comment]
Ahh nice. We were once looking at merging the projects. We never did though...

**Comment by lwoggardner** [comment]
The rake task in 1.x can *generate* yaml output - although it does that by calling to_json, then parsing the result into plain ruby objects, and then calling YAML.dump on that.  It does not use the special yaml syntax for Fn functions, nor can it carry comments.

We could rename JSONable to Templateable or similar, and implement corresponding to_yaml methods  but there is little support in Psych/YAML itself to manage things like comments so seems to be of little value.

Also the point of cfndsl is to allow maintainers to read the DSL rather than the output templates themselves.

This library does not read YAML or JSON -  that responsibility is currently with separate gem cfn2dsl.  That library seems like a candidate to bring under the cfndsl ownership in github, if folks were amenable to that,  but my view would be that it should stay as a separate gem.
