### ISSUE TITLE
Suggested way of splitting code to multiple files?

### ISSUE THREAD

**Issue by fgimian** [cfndsl/cfndsl#259]
Hey there, really great job on cfndsl 😄 

I just wanted to ask what the most common standards are with the library when trying to avoid a large cfndsl script.  Are you able to split a Cloudformation amongst multiple files in a directory structure (e.g. one for VPCs, one for subnets, .etc)?

Thanks heaps
Fotis

**Comment by kornypoet** [comment]
This has been discussed before, with various implementation options and ideas. It's something we would like to have implemented for the `1.0.0` release, but there has been no clear consensus on how to include resources across CloudFormation stacks. If you have any preferences, or ideas we would love to hear them.

**Comment by fgimian** [comment]
Thanks so much for your reply Travis, really appreciate it.

Honestly, I'm really not sure what would be the best way to split the code amongst multiple files.  However even the ability to logically separate everything into a few files and have it automatically combined for you would be a great start I think.

I'm currently using Terraform and really love it but am always keeping a keen eye on Cloudformation DSLs in case we encounter any big problems with Terraform.

Kindest Regards
Fotis

**Comment by ampedandwired** [comment]
There was some good discussion of various options in #151.

I tend to use [this approach](https://gist.github.com/ampedandwired/bd79023a305fcfc493857af0fed19b99) to decompose my templates into smaller files. It has the advantage that you can reuse the template fragments many times over with different parameters. Taking it to extremes you can even distribute pre-packaged cfndsl fragments in a gem that can then be included into other scripts by other teams.

I also try to have lots of small templates rather than few large ones. I find it helps when updating things. I use a tool called [Bora](https://github.com/ampedandwired/bora) (disclaimer - I'm the author) to wrangle all the different templates.

**Comment by adamhathcock** [comment]
I like the look of @ampedandwired 's multiple files.

I'm currently using terraform but thinking of moving back to cloud formation and really need to template some resources.

**Comment by lwoggardner** [comment]
This has always been possible (as commented above by @ampedandwired) because the DSL is just ruby and ruby already has the ability to load code via 'require'.
This is clearer now with the documentation for embedded ruby usage in the README so I think this one can be closed.
